    //Tabla Catalogo Departamento//
CREATE TABLE tbl_Cat_Departamento
(	idDepto NUMBER(10) NOT NULL ENABLE, 
	Descripcion VARCHAR2(200),
    Falta DATE DEFAULT SYSDATE,
    CONSTRAINT tbl_Cat_Departamento_PK PRIMARY KEY (idDepto));
        
 --CREACION DE SECUENCIA INCRMENTO 1---   
CREATE SEQUENCE INCREMDTO
START WITH 1
INCREMENT BY 1;

--TRIGEER PARA EL INCREMENENTO DE 1----

CREATE OR REPLACE TRIGGER TRGDPTO
BEFORE INSERT ON tbl_Cat_Departamento
FOR EACH ROW
BEGIN 
    SELECT INCREMDTO.NEXTVAL INTO  :NEW.idDepto FROM DUAL;    
END;

--PROCEDURE DE LA TABALA DEPTO----
CREATE OR REPLACE PROCEDURE SP_DEPTO_INSERT( DESCRIPCION IN VARCHAR2)
IS
BEGIN
insert into TBL_CAT_DEPARTAMENTO(DESCRIPCION) values (descripcion);
END SP_DEPTO_INSERT;

DESCRIBE TBL_CAT_DEPARTAMENTO;

--Llamar el procedure de DPTO---
EXECUTE SP_DEPTO_INSERT('CONTABILIDAD')


