   //Tabla Catalogo Departamento//
CREATE TABLE tbl_Cat_PERFIL
(	iPerfilId NUMBER(10) NOT NULL ENABLE, 
	Descripcion VARCHAR2(200),
    Falta DATE DEFAULT SYSDATE,
    CONSTRAINT tbl_Cat_PERFIL PRIMARY KEY (iPerfilId));
        
 --CREACION DE SECUENCIA INCRMENTO 1---   
CREATE SEQUENCE INCREMPFIL
START WITH 1
INCREMENT BY 1;

--TRIGEER PARA EL INCREMENENTO DE 1----

CREATE OR REPLACE TRIGGER TRGDPFIL
BEFORE INSERT ON tbl_Cat_PERFIL
FOR EACH ROW
BEGIN 
    SELECT INCREMPFIL.NEXTVAL INTO  :NEW.iPerfilId FROM DUAL;    
END;

