CREATE TABLE TBL_CAT_DEPARTAMENTO
   (ID_DEPTO NUMBER(10,0) NOT NULL ENABLE, 
	DESCRIPCION VARCHAR2(200 BYTE), 
	FALTA TIMESTAMP (6) DEFAULT (SYSDATE) NOT NULL ENABLE, 
	CONSTRAINT TBL_CAT_DEPARTAMENTO_PK PRIMARY KEY (ID_DEPTO));
	
	
	CREATE TABLE TBL_CAT_EMPLEADOS 
   (ID_CONS NUMBER(10,0) NOT NULL ENABLE, 
	CTA_USU_LOCAL VARCHAR2(10 BYTE), 
	NOMBRE VARCHAR2(100 BYTE), 
	APATERNO VARCHAR2(100 BYTE), 
	APMATERNO VARCHAR2(100 BYTE), 
	EDEPTO NUMBER(10,0), 
	DIRECCION VARCHAR2(200 BYTE), 
	TELEFONO VARCHAR2(14 BYTE), 
	CELULAR VARCHAR2(16 BYTE), 
	EMAIL VARCHAR2(100 BYTE), 
	FALTAE TIMESTAMP (6) DEFAULT SYSDATE, 
	CTA_USU_GLOBAL VARCHAR2(10 BYTE), 
	CONSTRAINT TBL_CAT_EMPLEADOS_PK PRIMARY KEY (CTA_USU_LOCAL));
	
	
	
	CREATE TABLE TBL_CAT_PERFIL 
   (IPERFILID NUMBER(10,0), 
	DESCRIPCIONPF VARCHAR2(200 BYTE) NOT NULL ENABLE, 
	FALTA DATE DEFAULT SYSDATE, 
	CONSTRAINT TBL_CAT_PERFIL PRIMARY KEY (IPERFILID));

