//CREACION DE LA BD DE GOLDEN SOURCE//


//Creacion del usuario//

CREATE USER SAMGSDB
IDENTIFIED BY SamgsDB
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA 20M ON USERS;



//Asignacion grants //

GRANT CREATE SESSION TO SAMGSDB;
GRANT CREATE TABLE TO SAMGSDB;
GRANT CREATE VIEW TO SAMGSDB;
GRANT CREATE PROCEDURE TO SAMGSDB;
GRANT CREATE SEQUENCE TO SAMGSDB;
GRANT CREATE INDEXTYPE TO SAMGSDB;
